apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frpc-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress-frp.labels" . | nindent 4 }}
data:
  frpc.ini: |
    [common]
    admin_addr=0.0.0.0
    admin_port={{ .Values.frp.frpc.port }}
    admin_user={{ .Values.frp.frpc.username }}
    admin_pwd={{ .Values.frp.frpc.password }}
    server_addr={{ .Values.frp.frps.addr }}
    server_port={{ .Values.frp.frps.port }}
    {{- if .Values.frp.token }}
    token={{ .Values.frp.token }}
    {{- end }}
    {{ if .Values.frp.tls.enable }}
    tls_enable = true
    tls_cert_file =/etc/ssh/frp/certificate.crt
    tls_key_file = /etc/ssh/frp/certificate.key
    tls_trusted_ca_file = /etc/ssh/frp/ca.crt
    {{- end }}