apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-frpc
  namespace: {{ .Release.Namespace }}
  labels:
    app: ingress-frpc
    {{- include "ingress-frp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ingress-frpc
      {{- include "ingress-frp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ingress-frpc
        {{- include "ingress-frp.selectorLabels" . | nindent 8 }}
      annotations:
        configmap-checksum: {{ include (print $.Template.BasePath "/configmap_frpc.yaml") . | sha256sum }}
    spec:
      containers:
      - name: ingress-frpc
        image: {{ .Values.frp.frpc.image.repository }}:{{ .Values.frp.frpc.image.tag }}
        imagePullPolicy: {{ .Values.frp.frpc.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - "mkdir /etc/frp; cp /etc/configmap/frpc.ini /etc/frp/frpc.ini && /usr/bin/frpc -c /etc/frp/frpc.ini"
        volumeMounts:
        - name: frpc-config
          mountPath: /etc/configmap
      {{- if .Values.frp.tls.enable }}
        - name: tls
          mountPath: /etc/ssh/frp
      {{- end }}
      volumes:
      - name: frpc-config
        configMap:
          name: {{ .Release.Name }}-frpc-config
          items:
          - key: frpc.ini
            path: frpc.ini
      {{- if .Values.frp.tls.enable }}
      - name: tls
        secret:
          secretName: {{ .Release.Name }}-tls
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.frp.frpc.nodeSelector | nindent 8 }}