apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-frp-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress-frp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-frp-leader-election-role
subjects:
- kind: ServiceAccount
  name: ingress-frp-controller-manager
  namespace: {{ .Release.Namespace }}