{{- if .Values.frp.tls.enable }}
apiVersion: v1
kind: Secret
data:
  ca.crt: {{ .Values.frp.tls.trustedCa }}
  certificate.crt: {{ .Values.frp.tls.cert }}
  certificate.key: {{ .Values.frp.tls.key }}
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
{{- end -}}
