apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frpc-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: ingress-frpc
    {{- include "ingress-frp.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.frp.frpc.port }}
    targetPort: {{ .Values.frp.frpc.port }}
    protocol: TCP
    name: web
  selector:
    app: ingress-frpc
      {{- include "ingress-frp.selectorLabels" . | nindent 4 }}