manager:
  image:
    repository: graydovee/ingress-frp
    tag: v0.0.1
    pullPolicy: IfNotPresent
  extraArgs: [ ]

frp:
  token:
  frpc:
    image:
      repository: graydovee/frpc
      tag: enchanced0.0.3
      pullPolicy: IfNotPresent
    addr:
    port: 7400
    username: admin
    password: admin
    nodeSelector: { }
  frps:
    addr: 8.8.8.8
    port: 7000
