---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - service
  verbs:
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingress
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingress/status
  verbs:
  - get
  - patch
  - update
